language: php
php:
  - '5.6'
  - '7'

services:
  - mysql

before_install:
#  - mysql -e "create database IF NOT EXISTS itb_test;" -uroot
  - mysql -u root -e "create database IF NOT EXISTS itb_test"
  - mysql -u root itb_test < itb_test.sql

install:
  - composer update

# before_script:
#  - mysql -u root itb_test < itb_test.sql

script:
  - phpunit

